version: 0.2

phases:
  install:
    commands:
      - echo Installing aws cli...
      - curl "https://s3.amazonaws.com/aws-cli/awscli-bundle.zip" -o "awscli-bundle.zip"
      - unzip awscli-bundle.zip
      - sudo ./awscli-bundle/install -i /usr/local/aws -b /usr/local/bin/aws
      - echo Installing Gatsby cli...
      - npm install -g gatsby-cli
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - gatsby build
  post_build:
    commands:
      - echo Build completed on `date`
      - aws codebuild list-builds
artifacts:
  files:
    - public/**/*