version: 0.2

phases:
  install:
    commands:
      - echo Installing Gatsby cli...
      - npm install -g gatsby-cli
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - gatsby build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Uploading folder to s3
      - aws s3 sync public/ s3://programmer-journey-blog-site/
artifacts:
  files:
    - public/**/*